# Generated by Django 4.0.4 on 2022-06-05 18:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(verbose_name='income')),
                ('date_added', models.DateField(verbose_name='date added')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Needs', 'Needs'), ('Wants', 'Wants')], max_length=255, verbose_name='category')),
                ('subcategory', models.CharField(choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Travel', 'Travel'), ('Housing', 'Housing'), ('Utility bills', 'Utility bills'), ('Cell phone', 'Cell phone'), ('Groceries', 'Groceries'), ('Clothing', 'Clothing'), ('Health care', 'Health care'), ('Child care', 'Child care'), ('Pet necessities', 'Pet necessities'), ('Pet insurance', 'Pet insurance'), ('Subscriptions', 'Subscriptions'), ('Others', 'Others')], max_length=255, verbose_name='subcategory')),
                ('price', models.IntegerField(verbose_name='price')),
                ('date_bought', models.DateField(verbose_name='date bought')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs', models.IntegerField(verbose_name='needs')),
                ('wants', models.IntegerField(verbose_name='wants')),
                ('savings', models.IntegerField(verbose_name='savings')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(verbose_name='balance')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,16}$')], verbose_name='NIK')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('needs_split', models.IntegerField(verbose_name='needs percentage')),
                ('wants_split', models.IntegerField(verbose_name='wants percentage')),
                ('savings_split', models.IntegerField(verbose_name='savings percentage')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
